### ISSUE TITLE
JsonReaders nextValue incorrectly escapes decimal numbers

### ISSUE THREAD

**Issue by richturner** [nmorel/gwt-jackson#108]
Example JSON: 

```
[123.134]
```

Call the following on the number token:

```reader.nextValue()```

Returns following string:

```"123.134"```

Should return following string:

```123.134```

**Comment by nmorel** [comment]
Hello, I merged your PR.  
Thanks for your work and sorry for the very long wait.  

A snapshot should be available soon.  
But it will be harder to make a release :/  
The maven plugin release used is outdated and I no longer have an environment to build a release.  
Last time I tried, it was the signature with gpg that failed.

**Comment by richturner** [comment]
Hi,

No worries, long term I'm hoping to eradicate GWT code from the codebase but tools like this are invaluable when working with GWT.

**Comment by nmorel** [comment]
Well, I can't make snapshot anymore it seems. The build on Travis is broken.  
Java 8 is no longer supported and on jdk 9+, a class was moved/removed and the tests fails.
