### ISSUE TITLE
Custom (de)serializer isn't picked upt because of "Cannot find the type denoted by the class"

### ISSUE THREAD

**Issue by ge0ffrey** [nmorel/gwt-jackson#110]
While trying to plug in a customer serializer and deserializer, during the gwt compilation I get this error, although the java compilation works and those 2 classes (LocalDateTimeJsonSerializer etc) exist:

```
[INFO]       Rebinding org.optaplanner.openshift.employeerostering.shared.rest.RosterServiceBuilder.ObjectReader2
[INFO]          Invoking generator com.github.nmorel.gwtjackson.rebind.ObjectMapperGenerator
[INFO]             [WARN] Cannot find the type denoted by the class org.optaplanner.openshift.employeerostering.shared.gwtjackson.LocalDateTimeJsonSerializer
[INFO]             [WARN] Cannot find the type denoted by the class org.optaplanner.openshift.employeerostering.shared.gwtjackson.LocalDateTimeJsonDeserializer
```

**Any idea what could be causing this?** If there's a common cause, it would be nice to improve the error message with that suggestion.

FWIW, here's my source code:
  https://github.com/ge0ffrey/optaplanner-openshift-worker-rostering/tree/develop/employee-rostering-oaas-gwtui/src/main
I am using the tbroyer gwt-maven-plugin, and I don't have a "client" package - but even when I do create a client package, rebind package, etc, the same error appears.

**Comment by nmorel** [comment]
Does the rest of the module works ?  
The position of the module.gwt.xml file seems odd and the `<source path=""/>` + `<super-source path="emulate" />` too.

**Comment by ge0ffrey** [comment]
Yes, the rest of the module works - I can deploy etc, it's only when a LocalDateTime is deserialized it errors out.

That gwt.xml position is due to the tbroyer plugin (which will replace the mojo gwt-maven-plugin).
See https://tbroyer.github.io/gwt-maven-plugin/ (and mojo plugin readme which notes that it will be replaced).

Source path is "", but I refactored to client (did all the adjustments) and that didn't make a difference. If needed, I can do that anyway, just to stick to conventions.

Super sources are independent of rebindings, right?

**Comment by nmorel** [comment]
Can you try to make a custom deserializer for Integer for example ?  
If it works, it's probably a problem on your super sources

**Comment by ge0ffrey** [comment]
Looks like you're right.
Using a custom JsonSerializer copy pasted from yours compiles without warnings:

    protected void configure() {
        primitiveType( int.class ).serializer( MyIntegerJsonSerializer.class ).deserializer( MyIntegerJsonDeserializer.class );
//        type(LocalDateTime.class).serializer(LocalDateTimeJsonSerializer.class).deserializer(LocalDateTimeJsonDeserializer.class);
    }

**Comment by ge0ffrey** [comment]
It's due to an import in that class:

```
import java.time.LocalDateTime; // This is fine
import java.time.format.DateTimeFormatter; // THIS IS THE PROBLEM

...

public class LocalDateTimeJsonDeserializer extends JsonDeserializer<LocalDateTime> {

    @Override
    protected LocalDateTime doDeserialize(JsonReader reader, JsonDeserializationContext ctx, JsonDeserializerParameters params) {
        return LocalDateTime.parse(reader.nextValue(), DateTimeFormatter.ISO_LOCAL_DATE_TIME);
    }

}
```

which causes

```
[WARN] Cannot find the type denoted by the class org...LocalDateTimeJsonDeserializer
```

Notice that that import class DateTimeFormatter isn't used in a generic type or anything for LocalDateTimeJsonDeserializer, so that warning is misleading. **Is there any way we could get the warning message to include the word "DateTimeFormatter"?**

Looking at the code where it logs that warning, it doesn't have the real error, it just sees mapperType is null:

```
        JClassType mapperType = context.getTypeOracle().findType( clazz.getCanonicalName() );
        if ( null == mapperType ) {
            logger.log( Type.WARN, "Cannot find the type denoted by the class " + clazz.getCanonicalName() );
         ...}
```

That TypeOracle.findType() method is a black box... any way to extract what went wrong in there?

**Comment by nmorel** [comment]
I don't think that's possible. The findType doesn't even throw an exception. There is no error to parse.

**Comment by ge0ffrey** [comment]
I've asked on StackOverflow:
http://stackoverflow.com/questions/43674908/gwt-rebinder-typeoracle-gettypefoo-foo-returns-null-how-to-get-the-real-er

Closing this issue meanwhile - I can reopen if there's an answer.

**Comment by ge0ffrey** [comment]
PR to improve the error message: https://github.com/nmorel/gwt-jackson/pull/111
