### ISSUE TITLE
Help - I already emulate UUID

### ISSUE THREAD

**Issue by shauntarves** [nmorel/gwt-jackson#116]
I'm trying to use this package via restgwt and the emulated UUID class is colliding with my own emulated UUID class. I need my version because I also emulate some of the constructors and getters for working with the lsb and msb long fields. When I inherit gwt-jackson, it doesn't seem to matter where I put it in my module.xml file, your UUID seems to be the one used and I get compilation errors. Is there a way to exclude your super-source directive in favor of my own?

**Comment by nmorel** [comment]
I don't know if that's possible.  
If you want, you can make a PR to split the super folder in two. One with jackson super source and one with uuid source.  
Then you make a gwt.xml file without the super uuid and one with it ?  
Or if you know a better solution backward compatible.

**Comment by blop** [comment]
I have the exact same issue.
It seems the only way is to fork gwt-jackson and remove/split their UUID implementation.

**Comment by blop** [comment]
I made a small project that provides a more complete UUID implementation :
https://github.com/taktik/gwt-uuid

If you feel like improving the one embedded within gwt-jackson ;-)
