### ISSUE TITLE
SimpleBeanJacksonTest.testSerializeValue FAILURE

### ISSUE THREAD

**Issue by freddyboucher** [nmorel/gwt-jackson#120]
When I run `mvn clean install` on the head master 376868794d2e6055bd47fa36c227311b5761ffd0, I get a test FAILURE:

> Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.043 sec <<< FAILURE! - in com.github.nmorel.gwtjackson.jackson.mapper.SimpleBeanJacksonTest
testSerializeValue(com.github.nmorel.gwtjackson.jackson.mapper.SimpleBeanJacksonTest)  Time elapsed: 0.011 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<..."sqlDate":"2012-08-1[8]","sqlTime":"01:45:5...> but was:<..."sqlDate":"2012-08-1[9]","sqlTime":"01:45:5...>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.Assert.assertEquals(Assert.java:107)
	at com.github.nmorel.gwtjackson.shared.mapper.SimpleBeanJsonMapperTester.testSerializeValue(SimpleBeanJsonMapperTester.java:260)
	at com.github.nmorel.gwtjackson.jackson.mapper.SimpleBeanJacksonTest.testSerializeValue(SimpleBeanJacksonTest.java:32)

I think it happens since I upgraded JDK to 1.8.0_141.

**Comment by freddyboucher** [comment]
More detail: my computer timezone is AEST – Australian Eastern Standard Time / Eastern Standard Time (Standard Time)
I know there is an issue with GWT DateTimeFormat (see https://github.com/gwtproject/gwt/issues/8259)
Could it be related? Thanks

**Comment by freddyboucher** [comment]
Yes it's timezone related!
When I set my mac timezone to Paris, it works fine!

**Comment by nmorel** [comment]
Can you try by specifying the timezone in the pom please ? Like here : https://stackoverflow.com/a/23466219

**Comment by freddyboucher** [comment]
@nmorel 
Sorry didn't see your answer, I will test your it because I still face this issue when I'm running tests locally.
