### ISSUE TITLE
ClassNotFoundException super source

### ISSUE THREAD

**Issue by freddyboucher** [nmorel/gwt-jackson#121]
Hi,
I'm creating a new [gwt-jackson-objectify](https://github.com/freddyboucher/gwt-jackson/tree/objectify)
The extension seems to works fine and all the JUnit tests are ok!

But when I try to use this extension in a [side project](https://github.com/freddyboucher/gwt-storage-objectify/tree/gwt-jackson-objectify), it fails at compile time.

One particularity of my extension is it uses **super sources** and the below Stacktrace show a **NoClassDefFoundError** on one of my super Class.

To reproduce it just run `mvn clean install`

thanks for the help.

> [INFO] --- gwt-maven-plugin:1.0-rc-8:compile (default-compile) @ gwt-storage-objectify-client ---
[INFO] Compiling module com.project.App
[INFO]    Computing all possible rebind results for 'com.project.client.View.StoredUsersDecoder'
[INFO]       Rebinding com.project.client.View.StoredUsersDecoder
[INFO]          Invoking generator org.fusesource.restygwt.rebind.JsonEncoderDecoderGenerator
[INFO]             Generating: com.project.client.View_StoredUsersDecoder_Generated_ExtendedJsonEncoderDecoder_
[INFO]                checking: org.fusesource.restygwt.client.JsonEncoderDecoder, type: class com.google.gwt.dev.javac.typemodel.JParameterizedType
[INFO]    [ERROR] An internal compiler exception occurred
[INFO] com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:111)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:276)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JCastOperation.traverse(JCastOperation.java:76)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:118)
[INFO] 	at com.google.gwt.dev.jjs.ast.JDeclarationStatement.traverse(JDeclarationStatement.java:49)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContext.traverse(JModVisitor.java:88)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemove(JModVisitor.java:331)
[INFO] 	at com.google.gwt.dev.jjs.ast.JBlock.traverse(JBlock.java:94)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:139)
[INFO] 	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:135)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodBody.traverse(JMethodBody.java:83)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.visitChildren(JMethod.java:786)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:778)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:265)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.mainLoop(UnifyAst.java:1401)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst.exec(UnifyAst.java:896)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.unifyJavaAst(JavaToJavaScriptCompiler.java:1410)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.constructJavaAst(JavaToJavaScriptCompiler.java:1222)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:1140)
[INFO] 	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler.precompile(JavaToJavaScriptCompiler.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
[INFO] 	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:204)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:155)
[INFO] 	at com.google.gwt.dev.Compiler.compile(Compiler.java:144)
[INFO] 	at com.google.gwt.dev.Compiler$1.run(Compiler.java:118)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
[INFO] 	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
[INFO] 	at com.google.gwt.dev.Compiler.main(Compiler.java:125)
[INFO] Caused by: java.lang.NoClassDefFoundError: com/google/appengine/api/datastore/Key
[INFO] 	at com.github.nmorel.gwtjackson.objectify.rebind.ObjectifyConfiguration.configure(ObjectifyConfiguration.java:33)
[INFO] 	at com.github.nmorel.gwtjackson.client.AbstractConfiguration.<init>(AbstractConfiguration.java:121)
[INFO] 	at com.github.nmorel.gwtjackson.objectify.rebind.ObjectifyConfiguration.<init>(ObjectifyConfiguration.java:29)
[INFO] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[INFO] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[INFO] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[INFO] 	at java.lang.Class.newInstance(Class.java:442)
[INFO] 	at com.github.nmorel.gwtjackson.rebind.RebindConfiguration.getAllConfigurations(RebindConfiguration.java:268)
[INFO] 	at com.github.nmorel.gwtjackson.rebind.RebindConfiguration.<init>(RebindConfiguration.java:214)
[INFO] 	at com.github.nmorel.gwtjackson.rebind.ObjectMapperGenerator.generate(ObjectMapperGenerator.java:38)
[INFO] 	at com.google.gwt.core.ext.IncrementalGenerator.generateNonIncrementally(IncrementalGenerator.java:40)
[INFO] 	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:745)
[INFO] 	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle$Rebinder.rebind(StandardRebindOracle.java:78)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:262)
[INFO] 	at com.google.gwt.dev.shell.StandardRebindOracle.rebind(StandardRebindOracle.java:251)
[INFO] 	at com.google.gwt.dev.PrecompilationContextCreator$1.getAllPossibleRebindAnswers(PrecompilationContextCreator.java:86)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createStaticRebindExpression(UnifyAst.java:519)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.createRebindExpression(UnifyAst.java:487)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.maybeHandleMagicMethodCall(UnifyAst.java:415)
[INFO] 	at com.google.gwt.dev.jjs.impl.UnifyAst$UnifyVisitor.visit(UnifyAst.java:402)
[INFO] 	at com.google.gwt.dev.jjs.ast.JMethodCall.traverse(JMethodCall.java:265)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:361)
[INFO] 	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:273)
[INFO] 	... 40 more
[INFO] Caused by: java.lang.ClassNotFoundException: com.google.appengine.api.datastore.Key
[INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[INFO] 	... 65 more
[INFO]       [ERROR] at Set__com_project_shared_entities_User_Gen_GwtJackEncDec_.java(23): GWT.create(Set__com_project_shared_entities_User_Gen_GwtJackEncDec_$GwtJackMapper.class)
[INFO]          com.google.gwt.dev.jjs.ast.JMethodCall
[INFO]       [ERROR] at Set__com_project_shared_entities_User_Gen_GwtJackEncDec_.java(23): (Set__com_project_shared_entities_User_Gen_GwtJackEncDec_$GwtJackMapper) GWT.create(Set__com_project_shared_entities_User_Gen_GwtJackEncDec_$GwtJackMapper.class)
[INFO]          com.google.gwt.dev.jjs.ast.JCastOperation
[INFO]       [ERROR] at Set__com_project_shared_entities_User_Gen_GwtJackEncDec_.java(23): Set__com_project_shared_entities_User_Gen_GwtJackEncDec_$GwtJackMapper mapper__ = (Set__com_project_shared_entities_User_Gen_GwtJackEncDec_$GwtJackMapper) GWT.create(Set__com_project_shared_entities_User_Gen_GwtJackEncDec_$GwtJackMapper.class)
[INFO]          com.google.gwt.dev.jjs.ast.JDeclarationStatement
[INFO]       [ERROR] at Set__com_project_shared_entities_User_Gen_GwtJackEncDec_.java(19): <source info not available>
[INFO]          com.google.gwt.dev.jjs.ast.JBlock
[INFO]       [ERROR] at Set__com_project_shared_entities_User_Gen_GwtJackEncDec_.java(19): <source info not available>
[INFO]          com.google.gwt.dev.jjs.ast.JMethodBody
[INFO]       [ERROR] at Set__com_project_shared_entities_User_Gen_GwtJackEncDec_.java(19): open.java.util.Set__com_project_shared_entities_User_Gen_GwtJackEncDec_.decode(Lcom/google/gwt/json/client/JSONValue;)Ljava/util/Set;
[INFO]          com.google.gwt.dev.jjs.ast.JMethod
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] gwt-storage-objectify .............................. SUCCESS [  0.163 s]
[INFO] gwt-storage-objectify-shared ....................... SUCCESS [  1.187 s]
[INFO] gwt-storage-objectify-client ....................... FAILURE [ 15.031 s]
[INFO] gwt-storage-objectify-server ....................... SKIPPED
[INFO] ------------------------------------------------------------------------

**Comment by nmorel** [comment]
Just by looking at the code, I can't find what's wrong.  
I generated the jar and it contains everything.  
You sure your jar in local maven repository is up to date ?

**Comment by freddyboucher** [comment]
I found the issue!
In my **gwt-jackson-objectify** extension I just replace `<scope>provided</scope>` by `<scope>compile</scope>`:
```xml
    <dependency>
      <groupId>com.googlecode.objectify</groupId>
      <artifactId>objectify</artifactId>
      <version>5.1.21</version>
      <scope>compile</scope>
    </dependency>
```
