### ISSUE TITLE
HashMap <SimplePojo, Set <Integer>> ...does not serialize into Json

### ISSUE THREAD

**Issue by yasinmustafa** [nmorel/gwt-jackson#127]
As the title suggests. I have a pojo which does not serialize into Json correctly. The map attribute inside my pojo gets missed

The map is of the following type
`HashMap <SimplePojo, Set <Integer>>`

Where SimplePojo is a class with two String fields.

If I  change the map to be as follows then it works
`HashMap <String, Set <Integer>>`

**Comment by nmorel** [comment]
You have to provide a serializer for your `SimplePojo` : https://github.com/nmorel/gwt-jackson/wiki/Custom-serializers-and-deserializers

To avoid creating your own serializer, you can add a toString() method to your pojo and use the ToStringKeySerializer : 
```java
key( SimplePojo.class ).serializer( ToStringKeySerializer.class );
```

**Comment by yasinmustafa** [comment]
thanks!
