### ISSUE TITLE
Please REVERT the dependency on Jackson 2.9.*, Jackson 2.9.* is NOT compatible with GWT.

### ISSUE THREAD

**Issue by michael-newsrx** [nmorel/gwt-jackson#143]
> Task :compileGwt 
Compiling module com.newsrx.butter.Butter
   Tracing compile failure path for type 'com.fasterxml.jackson.annotation.JacksonInject'
      [ERROR] Errors in 'jar:file:/Users/jason/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.9.5/2fc22732b6e1e7b6ed5eebfab8866766bb3a84d/jackson-annotations-2.9.5-sources.jar!/com/fasterxml/jackson/annotation/JacksonInject.java'
         [ERROR] Line 166: The method format(String, Object, Boolean) is undefined for the type String
   Tracing compile failure path for type 'com.fasterxml.jackson.annotation.JsonSetter'
      [ERROR] Errors in 'jar:file:/Users/jason/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.9.5/2fc22732b6e1e7b6ed5eebfab8866766bb3a84d/jackson-annotations-2.9.5-sources.jar!/com/fasterxml/jackson/annotation/JsonSetter.java'
         [ERROR] Line 246: The method format(String, Nulls, Nulls) is undefined for the type String
   [ERROR] Aborting compile due to errors in some input files

**Comment by nmorel** [comment]
Hello,
There is a PR to fix the issue : https://github.com/nmorel/gwt-jackson/pull/142
I just need to find time to release an other version.

**Comment by nmorel** [comment]
PR merged and 0.15.2 released.
