### ISSUE TITLE
Getter returning Optional<T> of nullable T causing compilation error

### ISSUE THREAD

**Issue by fr3driiik** [nmorel/gwt-jackson#149]
Hi!

I'm having some troubles with class containing fields that are nullable and getters for those that return Optional<T>:

```
class Car {
    String someOptionalText;

    public Optional<String> getSomeOptionalText() {
        return Optional.ofNullable(someOptionalText);
    }
}
```

This causes the following error: 

> [ERROR] Line xx: Type mismatch: cannot convert from String to Optional&lt;String&gt;

Looking at the generated Serializer I see that it contains the following:

```
@Override
public Optional<String> getValue(Car bean, JsonSerializationContext ctx) {
    return getValueWithJsni(bean);
}

private native String getValueWithJsni(Car bean) /*-{
    return bean.@the.package.Car::someOptionalText;
}-*/;
```
Which of course isn't working. 

I've used the following config:

```
public class JacksonGWTConfig extends AbstractConfiguration {
    @Override
    protected void configure() {
        fieldVisibility(Visibility.ANY);
        getterVisibility(Visibility.NONE);
        isGetterVisibility(Visibility.NONE);
        setterVisibility(Visibility.NONE);
    }	
}
```
Looking in the code for method parse in PropertyParser I see that it uses the help method parseMethods, which doesn't care about the configuration. So it uses my getter that has a different return type (Optional) and later uses this as the return type for the Serializer.. 

Can this be solved with some config, is this a bug or is there something else I'm missing?

**Comment by nmorel** [comment]
It's a bug and an edge case I think.  
It's rare to have a field and a getter with different type.     
But with getterVisibility set to NONE, the generator should only see the field and don't use Optional<String> at all. The getValue of the generated serializer should be a String.  

To solve it without fixing the bug, the easiest way would be to rename your getter.   
You can also try @JsonProperty with different names on the field and getter.   
Or change the visibility of getter to ANY but it will require a setter taking Optional<String> if you want to deserialize it.

I also accept PR :)
