### ISSUE TITLE
Collections serialization

### ISSUE THREAD

**Issue by reinert** [nmorel/gwt-jackson#35]
Are there any difference in the de/serialization process of Set, List and any of these implementations?

**Comment by reinert** [comment]
FYI, [requestor](https://github.com/reinert/requestor) was [officially released yesterday](https://groups.google.com/forum/#!topic/google-web-toolkit/IuFQlobR83U). It has an extension integration the HTTP Client API to gwt-jackson, making a really powerful union.

**Comment by nmorel** [comment]
Yep, I saw your post on G+.
I read a bit the documentation and read how to use gwt-jackson.
Do we need to annotate every single POJO or only the root one ?

**Comment by nmorel** [comment]
Also, I may add a simple example using requestor as I did for gwtp. This way, I can see if I break anything.

**Comment by reinert** [comment]
The way you can tell Requestor to generate and automatically register serializer and deserializer for a type is annotating it with `@Json`. This was the easiest way I found to provide auto serialization for custom types. Without any information in the types, or about them anywhere else, it was hard to automatically provide serialization for them. So, yes, it's necessary to annotate each POJO you want to have auto serialization. (The same procedure works for the AutoBeans integration, but instead of POJOs one should annotate only Interfaces)

I thank you for exposing requestor here.
