### ISSUE TITLE
How can I covert Object to List<String> ?

### ISSUE THREAD

**Issue by doggie1989** [nmorel/gwt-jackson#38]
I am using resty-gwt and it i depends on your project.

I use Map<String,Object> as DTO both in server side and client side.

GWT

``` java

@Path("http://localhost:8081")
public interface WhService extends RestService {

  @POST
  @Path("/{methodUrl}")
  public void postRequest(@PathParam("methodUrl") String methodUrl,Map<String,Object> request,MethodCallback<Map<String, Object>> callback);


}
```

if the Object is String, I can convert it into String type.
But,if the Object is List, when i use

``` java

 (List<String>) whProduct.get("infoUrls")  //this one not work,java.lang.ClassCastExceptio

String sku = whProduct.get("sku"); //this one work.
```

**Comment by reinert** [comment]
As an alternative, you could try [requestor](https://github.com/reinert/requestor). [It is integrated to gwt-jackson too](https://github.com/reinert/requestor/wiki/POJO-JSON-Serialization).

**Comment by nmorel** [comment]
I'll add frameworks using gwt-jackson to the README
