### ISSUE TITLE
Serializing some other object in custom serializer

### ISSUE THREAD

**Issue by butlnor** [nmorel/gwt-jackson#45]
Hello!

I don't find a way how to serialize some other object inside the "doSerialize" method of my custom serializer that extends JsonSerializer. 

Let's say I have classes A and B, and A contains field of type B. Now I have custom JSON serializers for both classes A and B and inside AJsonSerializer's doSerialize, I want to write the value of field B.

The thing is, I don't want to write B's fields inside the A's serializer, as in the real life the structure is much more complicated and a class like A contains many other objects. So serializer should be able to delegate each object's writing to its own serializer.

Example:

public class AJsonSerializer extends JsonSerializer<A> {
	@Override
	protected void doSerialize(JsonWriter writer, A value, JsonSerializationContext ctx, JsonSerializerParameters params) {
		writer.beginObject();
		writer.name("b");
		// writer.value(value.getB()); <-- here I want to serialize B with its own custom serializer
		writer.endObject();
	}
}

**Comment by nmorel** [comment]
A possible workaround is to define an `ObjectWriter` for B inside your `AJsonSerializer` and to retrieve the underlying serializer. 

```java
public class AJsonSerializer extends JsonSerializer {

    static interface BJsonWriter extends JsonWriter<B> {}

    private static final AJsonSerializer INSTANCE = new AJsonSerializer();

    private final JsonSerializer<B> bJsonSerializer;

    public static AJsonSerializer getInstance() {
        return INSTANCE;
    }

    private AJsonSerializer() {
        this.bJsonSerializer = (GWT.<AbstractObjectWriter>create( BJsonWriter.class )).getSerializer();
    }

    @Override
    protected void doSerialize( JsonWriter writer, A value, JsonSerializationContext ctx, JsonSerializerParameters params ) {
        writer.beginObject();
        writer.name( "b" );
        writer.value(bJsonSerializer.serialize( writer, value.getB(), ctx, params);
        writer.endObject();
    }
}
```

A bit more background about this issue : #40

I may add some factory interface where you could define all the serializer/deserializer you need.

**Comment by nmorel** [comment]
Can I ask why you need to define a custom serializer for your type A ?
You couldn't achieve it with annotations ?

**Comment by butlnor** [comment]
Wow thanks, that was what I was looking for. This works (except I had to use ObjectWriter<B> instead of JsonWriter<B>).

The reason for not using the annotations is, that the classes are in other older shared library projects, which must not have JSON annotations, as that projects are used elsewhere with custom build scripts, etc... So it's quite a requirement to leave the classes intact and not using additional dependencies.

I am very grateful, thanks.

**Comment by nmorel** [comment]
You can use [mixin annotation](https://github.com/nmorel/gwt-jackson/wiki/Mix-in-annotations) when you can't modify the class.

**Comment by butlnor** [comment]
The problem is that the classes don't have proper getters and setters (non-getter methods start with "get", but must not be called outside of their context, as they throw exceptions), but the fields are private or protected, so they cannot be serialized by the standard serializer. It's related to my previous issue.
