### ISSUE TITLE
Disable "Enum" and "EnumMap" warnings

### ISSUE THREAD

**Issue by butlnor** [nmorel/gwt-jackson#47]
If I have a Map<> that contains some wildcard parameterized type as a value, like:
    
    Map<String, List<SomeClass<?>>>

then I get warnings like:

    Type 'java.lang.Enum' is not supported as map's key
    Subtype 'java.util.EnumMap' is not supported. We ignore it.

I know it's just a warning and since my parameter will never be an Enum or EnumMap, I can ignore it. But this warning still puts junk into the log. And this happens for every such Map. So with many Maps, I get many warnings.

Is there any way to disable or hide it?

**Comment by nmorel** [comment]
I can change the log to info.

**Comment by butlnor** [comment]
Yes, to have it as an info is a possibility.

However, in my humble opinion, I think that it's quite unlikely that someone would use EnumMap as a wildcard parameter. They might use Enum, though, but rarely. But, I think, the warning about this can be clearly written somewhere in the documentation, and the generator could simply ignore it (by not logging this warning and not generating mappers for Enum and EnumMap).
However, the generator must fail with an error, if someone explicitly uses Enum or EnumMap in such a case.
What do you think?

**Comment by nmorel** [comment]
The generator does not fail but ignore the type when he does not support it. 

To remove the warning, I filtered out `EnumSet` and `EnumMap` from supported subtypes of `Object` and `Serializable` classes.

**Comment by butlnor** [comment]
Thanks, that's great! I am very grateful.
