### ISSUE TITLE
@JsonIdentityInfo with custom serializer/deserializer for ID property

### ISSUE THREAD

**Issue by butlnor** [nmorel/gwt-jackson#50]
I found another issue. 

If using @JsonIdentityInfo, to eliminate serializing the same instances of objects, gwt-jackson doesn't work, if "id" property is a parameter of the @JsonCreator constructor. I get an error:

* com.github.nmorel.gwtjackson.client.exception.JsonDeserializationException: java.lang.NullPointerException
	* at com.github.nmorel.gwtjackson.client.JsonDeserializationContext.traceError(JsonDeserializationContext.java:213)
	* at com.github.nmorel.gwtjackson.client.JsonDeserializationContext.traceError(JsonDeserializationContext.java:228)
	* at com.github.nmorel.gwtjackson.client.AbstractObjectMapper.read(AbstractObjectMapper.java:81)
	* at com.github.nmorel.gwtjackson.client.AbstractObjectMapper.read(AbstractObjectMapper.java:44)

I prepared a simplified test case (I omitted the obvious imports and other non-important code).
I have a simple TestDto, which has a list of "X" objects.

```java
public class TestDto {
	public List<X> list;
}

@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="id")
public class X {
	public String id;
	public String value;

	public X() {
	}

	@JsonCreator
	public X(@JsonProperty("id") String id) {
		this.id = id;
	}

	@JsonProperty
	public void setId(String id) {
		this.id = id;
	}
}
```

The input JSON string that I try to deserialize into TestDto:

```javascript
{
  "list" : 
  [ 
    {
      "id" : "1",
      "value" : "abc"
    }, 
    {
      "id" : "2",
      "value" : "test"
    }, 
    "1" 
  ]
}
```

However, if I remove "id" property from @JsonCreator, then it works. 

The problem is that gwt-jackson generator doesn't include the properties that are parameters of @JsonCreate in the "AbstractBeanJsonDeserializer.initDeserializers" method. But @JsonIdentityInfo needs such a property to be included in the list of deserializers. The "setId" setter in my example is there only to demonstrate that even an explicit setter doesn't force the property's deserializer to be added to the list.

So I guess gwt-jackson should either include all the properties in the list of deserializers (would cause a small overhead, that would be later eliminated by gwt compiler), or at least those that are referenced by @JsonIdentityInfo.

**Comment by butlnor** [comment]
I am apologizing, the problem was in our Identifier, which didn't have "equals" method properly working. Closing this non-issue. Sorry.

**Comment by butlnor** [comment]
I rewrote the issue text, as previously I haven't yet found the exact problem.

**Comment by butlnor** [comment]
Any estimates when this might get fixed? We are working on a big enterprise project, that has to be deployed soon, but some of our JSONs contain cyclical references...

**Comment by nmorel** [comment]
I'll take a look this week-end. Sorry for the delay but I haven't much free time currently.

For cyclic reference, did you take a look at @JsonBackReference and @JsonManagedReference ? 

As a workaround, can't you use the default constructor with the field private and annotation on it ? Or your fields are private ?

**Comment by butlnor** [comment]
Thanks a lot. 

Currently it's difficult to make overrides in our code, as those base classes are parts of the core, which is used in many different projects by many different developers. And those base classes have the ID in the constructors, as they require ID to be immutable. So even the extended classes must provide such ID via the constructors.

I haven't used @JsonBack/ManagedReference. On the server side, those cyclic references are properly serialized with just using @JsonIdentityInfo. Because the data hierarchy is such that no value is needed before it's defined. Will check @JsonBack/ManagedReference, if I'll find a case when it won't work by default.

**Comment by nmorel** [comment]
It's longer than I thought to fix the issue. 
I'm able to read the property but it is not enough. I don't save the instance inside the context as I don't find the property.

**Comment by nmorel** [comment]
A bit late now but it should work.
