### ISSUE TITLE
A question about the creation of Beans

### ISSUE THREAD

**Issue by BenDol** [nmorel/gwt-jackson#55]
I noticed that currently beans are created via 'new' keyword, my question is can we configure an object type to invoke a GWT.create creation? I'm not too well versed with GWT generators but I want my objects to automatically call this when created from the server, since they need to be deferred and rebound with another generator.

Is this possible or even logical? Thanks!

**Comment by nmorel** [comment]
You can use a @JsonCreator annotation on a static method and call GWT.create yourself.
Something like this :

```java
public class MyClass {

  @JsonCreator
  public static MyClass newInstance() {
    return GWT.<MyClass> create(MyClass.class);
  } 

  public MyClass() {
  }

}

```

**Comment by BenDol** [comment]
Thanks for the reply! Will test it out now :+1:

**Comment by BenDol** [comment]
This tries to call on the server too. Is there a way to stop it from calling it on the server?

**Comment by BenDol** [comment]
So I just changed it to:
```java
    @JsonCreator
    public static Setting newInstance() {
        return GWT.isClient() ? GWT.<Setting>create(Setting.class) : new Setting();
    }
```
and it works perfectly! Thanks @nmorel you're awesome hah

**Comment by BenDol** [comment]
I wonder if there's a global way to do this for the client side?

**Comment by nmorel** [comment]
No global way currently, sorry
