### ISSUE TITLE
Error compiling generated ObjectMapper with Java7

### ISSUE THREAD

**Issue by madbrain** [nmorel/gwt-jackson#62]
Modification in version 0.10.0 generate ObjectMapper for Enum which can't be compiled with Java7

```
Tracing compile failure path for type 'com.gwtplatform.dispatch.rest.client.serialization.mappers.com_example_service_dto_ApplicationTypeEnumMapperImpl'
    [ERROR] Errors in 'C:\Users\admin\AppData\Local\Temp\gwt-codeserver-7728558063367243075.tmp\com.example.gwt.ExampleMain\compile-2\gen\com\gwtplatform\dispatch\rest\client\serialization\mappers\com_example_service_dto_ApplicationTypeEnumMapperImpl.java'
        [ERROR] Line 23: Type mismatch: cannot convert from EnumJsonSerializer<capture#1-of ?> to JsonSerializer<ApplicationTypeEnum>
```

I found a workaround by overriding the default serializer for Enum and changing the `getInstance` method to return a simpler type :
```java
@SuppressWarnings("unchecked")
public static <S> JsonSerializer<S> getInstance() {
    return (JsonSerializer<S>) INSTANCE;
}
```

Hope this would help.

**Comment by nmorel** [comment]
Thanks, I'll take a look :)

**Comment by nmorel** [comment]
I couldn't reproduce but I applied your fix and saw no difference in my tests.
A version `0.10.1-SNAPSHOT` should be available soon with it.

**Comment by madbrain** [comment]
Sorry, I should have check the master branch, the modification you made in commit dda64ac288a7590f4b8d6cc2fc9a1bdf942409c6 to `ObjectMapperCreator` already fixed the problem, use of wildcard in generic parameter seems to please Java7 compiler.

You may however consider to add the following test:
```java
public class EnumMapperTest extends GwtJacksonTestCase {

    public static interface EnumMapper extends ObjectMapper<AnEnum> {
        static EnumMapper INSTANCE = GWT.create(EnumMapper.class);
    }

    public void testSerializeValue() {
        ObjectWriterTester<AnEnum> writer = createWriter(EnumMapper.INSTANCE);
        assertEquals("\"A\"", writer.write(AnEnum.A));
    }
}
```
as it was failing before that commit.

**Comment by nmorel** [comment]
Thanks for the test! I added it and rollback the previous fix.
I'm going to make a new release (0.11.0).
