### ISSUE TITLE
JsonTypeInfo cannot be deserialized

### ISSUE THREAD

**Issue by yissachar** [nmorel/gwt-jackson#64]
I have the following POJOS:

Message.java

```
public class Message {

    private String message;

    // getter + setter
}
```

Data.java

```
public class Data {

    @JsonTypeInfo(use = JsonTypeInfo.Id.CLASS)
    private Object data;

    // getter + setter
}
```

My expectation is that I can use my Data class to store any POJO and it will be deserialized correctly because of JsonTypeInfo annotation. When I use Jackson this works as expected:

```
ObjectMapper mapper = new ObjectMapper();
String json = "{\"data\":{\"@class\":\"com.foo.Message\",\"message\":\"Hello\"}}";
Data data = mapper.readValue(json, Data.class);
System.out.println(data.getData().getClass()); // com.foo.Message
```

But when using GWT-Jackson to do the same thing I receive an exception:

```
interface DataMapper extends ObjectMapper<Data> {
}

// ...

DataMapper mapper = GWT.create(DataMapper.class);
String json = "{\"data\":{\"@class\":\"com.foo.Message\",\"message\":\"Hello\"}}";
Data data = mapper.read(json);
```

> Uncaught com.google.gwt.event.shared.UmbrellaException: Exception caught: Could not find the type associated to com.foo.Message

**Comment by nmorel** [comment]
Try to [whitelist](https://github.com/nmorel/gwt-jackson/wiki/Type-support#object-and-serializable-support) the items.

**Comment by yissachar** [comment]
That doesn't seem to help:

```
public class CustomJacksonConfig extends AbstractConfiguration {
    @Override
    protected void configure() {
        whitelist("com\\.foo\\.Message");
    }
}
```

And added to gwt.xml as:

`<extend-configuration-property name="gwtjackson.configuration.extension"
                                   value="com.foo.CustomJacksonConfig"/>`

**Comment by nmorel** [comment]
And if you put the full path ? 
```java
whitelist("com.foo.Message");
```

**Comment by nmorel** [comment]
I use [RegexFilter](http://www.gwtproject.org/javadoc/latest/com/google/gwt/util/regexfilter/RegexFilter.html) internally.
There is a few examples [here](https://code.google.com/p/google-web-toolkit/issues/detail?id=4438).

**Comment by yissachar** [comment]
Sorry, the one I posted before (`whitelist("com\\.foo\\.Message");`) actually works. Something in my build was caching incorrectly and not picking up the changes. Once I cleaned it up properly and started from scratch it worked. Thanks!

**Comment by dnouls** [comment]
Just wondering, why does gwt-jackson not automatically scan the compilation classpath for all classes extending from the given class and generate the whitelist from that ? Sure it impacts performance during compilation but the time I have lost hunting down all these small things in a large project using gwt-jackson is just more expensive.

**Comment by nmorel** [comment]
It scans all classes already except for Object and Serializable because, as you said, it impact the compilation time, the size of the generated JS and potentially the runtime performance too.
But feel free to whitelist everything if you prefer :) I just don't think that's a good default behaviour.

**Comment by dnouls** [comment]
You mean that you are generating serializers for alle possible classes ? or only those that are subclasses of classes that were annotated with the JsonTypeInfo ? I moved my app over to use GWTP (which uses gwt-jackson) and it seems to work fine. Really great work!

**Comment by nmorel** [comment]
Only the subclasses of classes used in (de)serialized property yes. For serialization, I generate for all subclasses even if not annotated.
The only exception is Object and Serializable.
