### ISSUE TITLE
JSON de serialization issue on GWT RPC calls

### ISSUE THREAD

**Issue by satiagomunez** [nmorel/gwt-jackson#65]
For the rest calls in GWT, POJO's was annotated as below
```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = Child1.class),
        @JsonSubTypes.Type(value = Child2.class)
})
public class Parent{
...
}
```
and child as
```
@JsonTypeInfo(use = JsonTypeInfo.Id.CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@type")
public class Child1 extends Parent {
}
```
and in the JSON response in client, we actually get the @type property and also the child fields respectively, but the when we do getClass it returns Parent.class and not the child classes.

Can you help here.

**Comment by nmorel** [comment]
If you add a property on Child1, it is present in the JSON response but the deserialization ignores it and creates a Parent ?  

Just by watching the 2 class you gave, I don't know where is the problem. The `@JsonTypeInfo` is not needed on Child1 but it should not be the problem.

Can you give me an example project ? You can use one of the examples of this project.

**Comment by satiagomunez** [comment]
If you add a property on Child1, it is present in the JSON response but the deserialization ignores it and creates a Parent ?
Yes! 

As I see its done by the org.fusesource.restygwt.client.AbstractRequestCallback#parseResult . But i dont find the implementation for this method.

**Comment by nmorel** [comment]
Oh wait, you are using RestyGWT ? :)
They don't use gwt-jackson. They have their own implementation.
