### ISSUE TITLE
Unable to deserialize response. An unexpected error occurred.

### ISSUE THREAD

**Issue by confile** [nmorel/gwt-jackson#66]
I tried to deserialize the following DTO: 

```
public class MessageDto extends BaseEntity {
 
  private MessageType type;

  public MessageType getType() {
    return type;
  }

  public void setType(MessageType type) {
    this.type = type;
  }
}
```

The dto contains an enum type ``MessageType``. How can I use this type for deserialization?

**Comment by nmorel** [comment]
Can you give me the definition of `MessageType` and `BaseEntity` please ?
And you should have more informations in the logs.

**Comment by confile** [comment]
Sure: 

```
public enum MessageType {

  test1(0), test2(1), test3(2);
  
  
  private final int value;
  
  private MessageType(int value) {
    this.value = value;
  }
  
  public int getValue() {
    return value;
  }
  
}
```

**Comment by nmorel** [comment]
Did you find a solution ?  
You didn't give the source of BaseEntity and the logs.

**Comment by confile** [comment]
No I did not find a solution. Do you have an example how it is done?

**Comment by nmorel** [comment]
To deserialize a DTO with an enum ? 
[This one](https://github.com/nmorel/gwt-jackson/blob/master/gwt-jackson/src/test/java/com/github/nmorel/gwtjackson/client/mapper/SimpleBeanObjectReaderTest.java)
Paste the full log, maybe I can find what's the problem.
