### ISSUE TITLE
Add support for auto generating a whitelist for polymorphic subtypes.

### ISSUE THREAD

**Issue by dnouls** [nmorel/gwt-jackson#70]
I am trying out different gwt rest APIs and they all seem to be incomplete. gwt-jackson seems the most complete but there is one thing missing:
A possibility to automate the generation of the whitelist of polymorphic objects.

GWT-resty support this by using a RestyJsonTypeIdResolver that can be associated with a custom jackson TypeIdResolver. This extra interface can either be directly implemented on the resolver class, or through a gwt.xml property it can be added in the serialisation process.
In this interface all you need to do is to generate a map of String,Class<?> of classes that should be allowed as subtypes. This map can be easily generated during the compile using Reflections searching for any class that extends/implements the basetype annotated with the JsonTypeInfo.

**Comment by nmorel** [comment]
I answered in https://github.com/nmorel/gwt-jackson/issues/64#issuecomment-201353573.
Can we close this ?

**Comment by dnouls** [comment]
yes you may close it. The answer is clear and sufficient for me.
