### ISSUE TITLE
JsonDeserialize annotation in super area is missing methods

### ISSUE THREAD

**Issue by francoisregis** [nmorel/gwt-jackson#76]
The annotation `com.github.nmorel.gwtjackson.super.com.fasterxml.jackson.databind.annotation.JsonDeserialize`
should have the same signature as the original annotation it supersedes.

Even if some of those methods are not (yet) supported by this framework they should at least be gracefully ignored at GWT compilation time.
For example we are using a custom serializer on the backend and we are using the `@JsonDeserialize` annotation with the `using` method.

```
@XmlEnum
@JsonDeserialize(using = StatusDeserializer.class)
public enum Status {
```

This leads to the following compilation error:

```
[ERROR] Line 15: The attribute using is undefined for the annotation type JsonDeserialize
```

Just adding the methods is enough to get by the compilation error.

**Comment by nmorel** [comment]
A snapshot should be available with your fix.
Thanks for the PR!
