### ISSUE TITLE
Line 203: No source code is available for type com.fasterxml.jackson.annotation.JacksonAnnotationValue<A>; did you forget to inherit a required module?

### ISSUE THREAD

**Issue by aliakhtar** [nmorel/gwt-jackson#78]
This is my first time using this library.

- Inherited the module in gwt.xml

- Created a pojo with a single String field, and a getter / setter for it. No annotations.

- Created an interface `MyProjoMapper` which extends from `com.github.nmorel.gwtjackson.client.ObjectMapper<MyPojo>`

- Created it using GWT.create(MyPojoMapper.class), and then tried `String json = mapper.write(pojo)`

When I attempt to run gwt in SDM, it fails with a lot of warnings, and the following errors:

 

>         [ERROR] Errors in 'com/github/nmorel/gwtjackson/super/com/fasterxml/jackson/annotation/JsonInclude.java'
>             [ERROR] Line 203: No source code is available for type com.fasterxml.jackson.annotation.JacksonAnnotationValue<A>; did you forget to inherit a required module?
>             [ERROR] Errors in 'com/github/nmorel/gwtjackson/super/com/fasterxml/jackson/annotation/JsonInclude.java'
>                [ERROR] Line 203: No source code is available for type com.fasterxml.jackson.annotation.JacksonAnnotationValue<A>; did you forget to inherit a required module?
>          [ERROR] Hint: Your source appears not to live underneath a subpackage called 'client'; no problem, but you'll need to use the <source> directive in your module to make it accessible

Here are the modules I'm inheriting:

```
    <inherits name='com.google.gwt.user.User' />
    <inherits name="com.google.gwt.logging.Logging"/>
    <inherits name="com.google.gwt.http.HTTP"/>
    <inherits name="com.google.gwt.precompress.Precompress"/>
    <inherits name="org.fusesource.restygwt.RestyGWT"/>
    <inherits name="com.google.web.bindery.autobean.AutoBean"/>
    <inherits name="org.realityforge.gwt.websockets.WebSockets"/>
    <inherits name="com.fasterxml.jackson.annotation.JacksonAnnotation" />
    <inherits name="com.github.nmorel.gwtjackson.GwtJackson" />
```

Any ideas? This is a little bit urgent, so a quick response would be greatly appreciated.

**Comment by nmorel** [comment]
Which version of GWT are you using ?  
Do you include the jar and source jar of jackson annotation ?  
Which version of jackson ?

You should remove the line 
```
<inherits name="com.fasterxml.jackson.annotation.JacksonAnnotation" />
```

It's already included in GwtJackson. Doesn't RestyGWT include gwt-jackson now ?

**Comment by nmorel** [comment]
I added an example using the last snapshot version of RestyGWT if you are still stucked : https://github.com/nmorel/gwt-jackson/tree/master/examples/restygwt

**Comment by aliakhtar** [comment]
Thank you. I haven't had time to look into this project recently. Will update when I get a chance.

I was using GWT 2.8.0-beta1, and the latest version of gwt-jackson as on maven central.

I'm using it in combination with RestyGWT but it didn't seem to add gwt-jackson to the classpath.

**Comment by nmorel** [comment]
RestyGWT only support it in the last snapshot, not the last stable.
