### ISSUE TITLE
Documentation for custom de/serializers is confusing for generic types / type arguments.

### ISSUE THREAD

**Issue by kmthinkingrock** [nmorel/gwt-jackson#84]
See issue [83](https://github.com/nmorel/gwt-jackson/issues/83) - documentation could be improved for this feature.

**Comment by nmorel** [comment]
Which part is confusing ?  
The one describing the static method inside (de)serializer use to instantiate the class ?

**Comment by kmthinkingrock** [comment]
> In the case of the type being a generic like java.util.List, the generator looks for a static method or a constructor having the same amount of parameters and with all the parameters extending com.github.nmorel.gwtjackson.client.JsonSerializer, com.github.nmorel.gwtjackson.client.JsonDeserializer, com.github.nmorel.gwtjackson.client.ser.map.key.KeySerializer or com.github.nmorel.gwtjackson.client.deser.map.key.KeyDeserializer

The sentence above. It wasn't clear to me that "the same amount of parameters" meant that the number of parameters for the static method or constructor had to match the number of type parameters used by the generic.

**Comment by nmorel** [comment]
I hope it's better now :)
