### ISSUE TITLE
Improve warning for "unable to instantiate" message related to custom serializers.

### ISSUE THREAD

**Issue by kmthinkingrock** [nmorel/gwt-jackson#85]
See [issue 83](https://github.com/nmorel/gwt-jackson/issues/83) - had to sprinkle debug messages in generator to determine root cause of warning.

**Comment by nmorel** [comment]
It's now a compile error if the configuration is incorrect and a link to the wiki page is logged

**Comment by kmthinkingrock** [comment]
Awesome!!
