### ISSUE TITLE
Compilation failure with gwt-2.8-rc1

### ISSUE THREAD

**Issue by crevete** [nmorel/gwt-jackson#89]
When I compile my project with **gwt-2.8-rc1** with https://gwt-maven-plugin.github.io/gwt-maven-plugin/, it fails with the following errors :
```
[INFO]    Computing all possible rebind results for 'com.google.gwt.user.client.ui.impl.TextBoxImpl'
[INFO]       Rebinding com.google.gwt.user.client.ui.impl.TextBoxImpl
[INFO]          Checking rule <replace-with class='com.github.nmorel.gwtjackson.client.JsonSerializationContext.DefaultBuilder'/>
[INFO]             [WARN] Unknown type 'com.github.nmorel.gwtjackson.client.JsonSerializationContext.Builder' specified in deferred binding rule
[INFO]          Checking rule <generate-with class='com.github.nmorel.gwtjackson.rebind.ObjectMapperGenerator'/>
[INFO]             [WARN] Unknown type 'com.github.nmorel.gwtjackson.client.ObjectWriter' specified in deferred binding rule
[INFO]       Rebinding com.google.gwt.user.client.ui.impl.TextBoxImpl
[INFO]          Checking rule <replace-with class='com.github.nmorel.gwtjackson.client.JsonSerializationContext.DefaultBuilder'/>
[INFO]             [WARN] Unknown type 'com.github.nmorel.gwtjackson.client.JsonSerializationContext.Builder' specified in deferred binding rule
[INFO]          Checking rule <generate-with class='com.github.nmorel.gwtjackson.rebind.ObjectMapperGenerator'/>
```
Then it results like this : 
```
 [ERROR] Errors in 'file:/home/xsun/workspace/portal/webapp/src/main/java/com/wallix/portal/app/client/SftpWebapp.java'
[INFO]             [ERROR] com.github.nmorel.gwtjackson.client.ObjectMapper cannot be resolved to a type
```
Do you have an idea? Is it possible to update the gwt version in gwt-jackson to support this ? As we need to use gwt-2.8. Thanks

FYI : With gwt 2.8-beta1, I've got this error :
```
[ERROR] Line 111: The method newInstance(JsonSerializer<T>) in the type ArrayJsonSerializer is not applicable for the arguments (EnumJsonSerializer<?>)
            [ERROR] Line 111: Type mismatch: cannot convert from EnumJsonSerializer<capture#2-of ?> to JsonSerializer<T>
```

**Comment by nmorel** [comment]
Did you try the latest snapshot ?  
The examples are compiled with the rc1

**Comment by crevete** [comment]
@nmorel It's better: the first error disapears. But I still got the second one:
```
[ERROR] Line 111: The method newInstance(JsonSerializer<T>) in the type ArrayJsonSerializer is not applicable for the arguments (EnumJsonSerializer<?>)
            [ERROR] Line 111: Type mismatch: cannot convert from EnumJsonSerializer<capture#2-of ?> to JsonSerializer<T>
```
In fact, in my model class (to be serialized), I have a field with Enum array type:
```
private MyField[] myFields;
```
In the GWT-generated JsonSerializerImpl class:
```
@Override
protected BeanPropertySerializer[] initSerializers() {
    BeanPropertySerializer[] result = new BeanPropertySerializer[10];
    ...
    result[7] = new BeanPropertySerializer<MyModel, MyModel.MyField[]>("myFields") {
      @Override
      protected JsonSerializer<?> newSerializer() {
        // Below is the line 111 and it does not compile
        return ArrayJsonSerializer.newInstance(EnumJsonSerializer.getInstance());
      }
      @Override
      public MyModel.MyField[] getValue(MyModel bean, JsonSerializationContext ctx) {
        return bean.getMyFields();
      }
    };
}
```

**Comment by nmorel** [comment]
I'm not sure I tested enum array. I got lots of issues with the `EnumJsonSerializer.getInstance()`method and I removed most of the type check to fix them. 

To bypass the error for now, you could create a custom serializer/deserializer using `MyField[].class` as type following these instructions : https://github.com/nmorel/gwt-jackson/wiki/Custom-serializers-and-deserializers

**Comment by crevete** [comment]
Yes, it was removed in the source code (It works fine wtth 0.13.0)
Thanks anyway, I will try to do it and give you a feedback later.

**Comment by crevete** [comment]
@nmorel The problem is: I got multiple enum array is my model, I don't think write a custom serializer for each enum array is a good idea... For me, it is a bug of gwt-jackson. I forgot to say that the compilation was done with JDK8. With JDK7 + gwt-jackson 0.13.0, it works fine.

**Comment by crevete** [comment]
@nmorel any news about this? It seems that it is just a generic issue. Thanks

**Comment by nmorel** [comment]
It should work now.  

I'll release a new version as soon as my CI starts working again. 
In the meantime, a snapshot is available.

**Comment by crevete** [comment]
Thanks!

**Comment by Martin-Wegner** [comment]
@nmorel any news on this issue?

**Comment by nmorel** [comment]
I didn't release a new version yet but I should have time this week-end.

**Comment by nmorel** [comment]
Version 0.14.1 released

**Comment by Martin-Wegner** [comment]
@nmorel thanks!
