### ISSUE TITLE
Integer with value 0 not serialized

### ISSUE THREAD

**Issue by blop** [nmorel/gwt-jackson#97]
It seems that field of type Integer with a zero value are not serialized.

com.github.nmorel.gwtjackson.client.ser.BaseNumberJsonSerializer.IntegerJsonSerializer threats 0 as a default value.
I understand why this can be the case for primitive type (int) but not for object Integer.

How can one differentiate between null and 0 in that case?

You should have different serializer for primitive number types and object number types.

Thanks

**Comment by blop** [comment]
Or better, how can we set the  JsonInclude.Include.NON_ABSENT as default for all objects, without having to add @JsonInclude on every class?

**Comment by blop** [comment]
I'd add that it seems dangerous to have 0 not serialized by default.

**Comment by nmorel** [comment]
Ah nice catch, you're right, it should be serialized.

Do you want to make a PR ? Just need to duplicate the serializer for each primitive value and update [DefaultConfiguration](https://github.com/nmorel/gwt-jackson/blob/master/gwt-jackson/src/main/java/com/github/nmorel/gwtjackson/rebind/DefaultConfiguration.java)

**Comment by blop** [comment]
I can do that yes

**Comment by nmorel** [comment]
Thanks :)  

To test it, the best place is probably [JsonIncludeTester](https://github.com/nmorel/gwt-jackson/blob/master/gwt-jackson/src/test/java/com/github/nmorel/gwtjackson/shared/annotations/JsonIncludeTester.java).

For GWT : [JsonIncludeGwtTest](https://github.com/nmorel/gwt-jackson/blob/master/gwt-jackson/src/test/java/com/github/nmorel/gwtjackson/client/annotation/JsonIncludeGwtTest.java)
For Jackson : [JsonIncludeJacksonTest](https://github.com/nmorel/gwt-jackson/blob/master/gwt-jackson/src/test/java/com/github/nmorel/gwtjackson/jackson/annotations/JsonIncludeJacksonTest.java)

This [test](https://github.com/nmorel/gwt-jackson/blob/master/gwt-jackson/src/test/java/com/github/nmorel/gwtjackson/shared/annotations/JsonIncludeTester.java#L142) should have catch the problem but it seems Jackson also consider 0 a default value for Integer.
